apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pendingqueue-service-deployment
  namespace: development
  labels:
    app: pendingqueue-service-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: pendingqueue-service
    spec:
      containers:
      - name: sqldb-service
        image: index.docker.io/v1/:proj/pendingqueue
        ports:
        - containerPort: 8082
